name: CI/CD
run-name: CI/CD for building docker image for oha-docker and push to docker hub.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_amd64:
    name: Build docker image and test for linux/amd64 architecture
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image for linux/amd64
        run: docker build --platform linux/amd64 -t oha-docker .

      - name: Check container works properly on linux/amd64
        run: docker run --rm oha-docker -n 10 -c 1 https://google.com

  test_arm64:
    name: Build docker image and test for linux/arm64 architecture
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image for linux/arm64
        run: |
          sudo apt update -y
          sudo apt install -y qemu qemu-user-static
          docker build --platform linux/arm64 -t oha-docker .

      - name: Check container works properly on linux/arm64
        run: docker run --rm oha-docker -n 10 -c 1 https://google.com

  build:
    name: Build docker image and push to docker hub
    runs-on: ubuntu-latest
    needs:
      - test_amd64
      - test_arm64
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ahmadalsajid/oha-docker:latest
            ahmadalsajid/oha-docker:debian-bookworm-slim-rust1.80-slim-bookworm
